[package]
name = "foo"
version = "0.1.0"
authors = ["panicbit <panicbit.dev@gmail.com>"]
edition = "2018"

[dependencies]
winapi = { version = "0.3.7", features = ["fileapi", "memoryapi", "ioapiset"] }
